# Generated by Django 6.0.7 on 2026-09-23 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collections_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectioncategoryitem',
            name='label_en',
        ),
        migrations.RemoveField(
            model_name='collectionindexpage',
            name='empty_state_text_en',
        ),
        migrations.RemoveField(
            model_name='collectionindexpage',
            name='hero_title_en',
        ),
        migrations.RemoveField(
            model_name='collectionindexpage',
            name='intro_text_en',
        ),
        migrations.RemoveField(
            model_name='collectionindexpage',
            name='search_description_en',
        ),
        migrations.RemoveField(
            model_name='collectionproductitem',
            name='image_alt_en',
        ),
        migrations.RemoveField(
            model_name='collectionproductitem',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='collectiontypeitem',
            name='label_en',
        ),
    ]
