# Generated by Django 6.0.7 on 2026-09-23 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_page', '0002_remove_collectioncategoryitem_label_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionproductitem',
            name='collection_category',
            field=models.ForeignKey(blank=True, help_text='Optional: select the category to avoid typing category_key.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='collections_page.collectioncategoryitem'),
        ),
        migrations.AddField(
            model_name='collectionproductitem',
            name='collection_type',
            field=models.ForeignKey(blank=True, help_text='Prefer selecting a type instead of typing type_key.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='collections_page.collectiontypeitem'),
        ),
        migrations.AddField(
            model_name='collectiontypeitem',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Prefer selecting a category instead of typing the key manually.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='collections_page.collectioncategoryitem'),
        ),
        migrations.AlterField(
            model_name='collectionproductitem',
            name='category_key',
            field=models.SlugField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='collectionproductitem',
            name='type_key',
            field=models.SlugField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='collectiontypeitem',
            name='category_key',
            field=models.SlugField(blank=True, max_length=80),
        ),
    ]
