# Generated by Django 6.0.7 on 2026-09-23 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collections_page', '0003_collectionproductitem_collection_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionproductitem',
            name='collection_category',
        ),
        migrations.RemoveField(
            model_name='collectionproductitem',
            name='collection_type',
        ),
        migrations.RemoveField(
            model_name='collectiontypeitem',
            name='category',
        ),
    ]
