# Generated by Django 6.0.7 on 2026-09-24 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_page', '0004_remove_collectionproductitem_collection_category_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionproductitem',
            name='back_to_menu_label',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='collectionproductitem',
            name='download_heading',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='collectionproductitem',
            name='download_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='collectionproductitem',
            name='gallery_pair',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='collectionproductitem',
            name='intro_text_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='collectionproductitem',
            name='intro_text_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='collectionproductitem',
            name='product_eyebrow',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='collectionproductitem',
            name='product_heading',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='collectionproductitem',
            name='secondary_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='collectionproductitem',
            name='technical_eyebrow',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='collectionproductitem',
            name='technical_image_dimensions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='collectionproductitem',
            name='technical_image_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
