# Generated by Django 6.0.7 on 2026-09-24 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_page', '0005_collectionproductitem_back_to_menu_label_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionproductitem',
            name='gallery_pair',
        ),
        migrations.AddField(
            model_name='collectionproductitem',
            name='gallery_image_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='collectionproductitem',
            name='gallery_image_1_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='collectionproductitem',
            name='gallery_image_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='collectionproductitem',
            name='gallery_image_2_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
