# Generated by Django 6.0.7 on 2026-09-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_page', '0006_remove_collectionproductitem_gallery_pair_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionproductitem',
            name='intro_text_product',
            field=models.TextField(blank=True),
        ),
    ]
