# Generated by Django 6.0.7 on 2026-09-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact_cms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactpage",
            name="project_button_label",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="contactpage",
            name="url_contact",
            field=models.URLField(blank=True),
        ),
    ]
