# Generated by Django 6.0.7 on 2026-09-17 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs_cms', '0001_initial'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogindexitem',
            name='file_document',
            field=models.ForeignKey(blank=True, help_text='Upload the PDF file to be downloaded from this catalog card.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
    ]
