# Generated by Django 6.0.7 on 2026-09-01 14:22

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='catalogs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image_horizontal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image_vertical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_video_horizontal',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_video_vertical',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='home_copy',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='homepage',
            name='site_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='values_slides',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='HomeFeaturedProjectItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_projects_items', to='home.homepage')),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomeTeamMemberItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(blank=True, max_length=150)),
                ('role_en', models.CharField(blank=True, max_length=150)),
                ('bio', models.TextField(blank=True)),
                ('bio_en', models.TextField(blank=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members_items', to='home.homepage')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
