# Generated by Django 6.0.7 on 2026-09-17 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_make_home_inline_items_translatable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='catalogs_dot_aria',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='catalogs_eyebrow',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='catalogs_heading',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='catalogs_next_aria',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='catalogs_prev_aria',
        ),
        migrations.DeleteModel(
            name='HomeCatalogItem',
        ),
    ]
