# Generated by Django 6.0.7 on 2026-09-17 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_homecatalogitem_homecatalogitem_translation_key_locale_uniq_and_more'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homecontactlinkitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='homefeaturedprojectitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hometeammemberitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='homevalueslideitem',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='homecontactlinkitem',
            name='homecontactlinkitem_translation_key_locale_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='homefeaturedprojectitem',
            name='homefeaturedprojectitem_translation_key_locale_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='hometeammemberitem',
            name='hometeammemberitem_translation_key_locale_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='homevalueslideitem',
            name='homevalueslideitem_translation_key_locale_uniq',
        ),
        migrations.AlterField(
            model_name='homecontactlinkitem',
            name='locale',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale'),
        ),
        migrations.AlterField(
            model_name='homefeaturedprojectitem',
            name='locale',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale'),
        ),
        migrations.AlterField(
            model_name='hometeammemberitem',
            name='locale',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale'),
        ),
        migrations.AlterField(
            model_name='homevalueslideitem',
            name='locale',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale'),
        ),
        migrations.AlterUniqueTogether(
            name='homecontactlinkitem',
            unique_together={('translation_key', 'locale')},
        ),
        migrations.AlterUniqueTogether(
            name='homefeaturedprojectitem',
            unique_together={('translation_key', 'locale')},
        ),
        migrations.AlterUniqueTogether(
            name='hometeammemberitem',
            unique_together={('translation_key', 'locale')},
        ),
        migrations.AlterUniqueTogether(
            name='homevalueslideitem',
            unique_together={('translation_key', 'locale')},
        ),
    ]
