# Generated by Django 6.0.7 on 2026-09-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_homecontactlinkitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_video_horizontal',
            field=models.FileField(blank=True, help_text='Video horizontal del hero.', null=True, upload_to='videos/home/'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_video_vertical',
            field=models.FileField(blank=True, help_text='Video vertical del hero.', null=True, upload_to='videos/home/'),
        ),
    ]
