# Generated by Django 6.0.7 on 2026-10-08 15:45

from django.db import migrations, models


def deduplicate_term_items_per_page(apps, schema_editor):
    TermItem = apps.get_model("terms_cms", "TermItem")

    groups = (
        TermItem.objects.values("page_id", "key")
        .order_by()
    )

    seen = set()
    for group in groups.iterator():
        identity = (group["page_id"], group["key"])
        if identity in seen:
            continue
        seen.add(identity)

        duplicates = list(
            TermItem.objects.filter(page_id=group["page_id"], key=group["key"])
            .order_by("sort_order", "pk")
            .values_list("pk", flat=True)
        )
        if len(duplicates) <= 1:
            continue

        TermItem.objects.filter(pk__in=duplicates[1:]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("terms_cms", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            deduplicate_term_items_per_page,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="termitem",
            constraint=models.UniqueConstraint(
                fields=("translation_key", "locale"),
                name="unique_translation_key_locale_terms_cms_termitem",
            ),
        ),
        migrations.AddConstraint(
            model_name="termitem",
            constraint=models.UniqueConstraint(
                fields=("page", "key"),
                name="terms_cms_termitem_unique_key_per_page",
            ),
        ),
    ]
